packages:
  # all packages in direct subdirs of apps/
  - "apps/*"
  # all packages in subdirs of packages/
  - 'apps/**'
  # all packages in direct subdirs of packages/
  - "packages/*"
  # all packages in subdirs of packages/
  - 'packages/**'
  # all packages in subdirs of tryoutprojects/
  - 'tryoutprojects/**'
  - "services/*"
  - '!**/apps/angular-spa-starter'
